<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{1f314313-d09b-4c20-80db-7ead9994caa1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbMotion: FB_MotionStage;
    fbMotionRequest_Test: FB_MotionRequest_Test;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbMotion(stMotionStage:=SIM.stBasicMotor);
TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>