<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{9bcc2915-7068-448d-a348-931c17fac05a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	M1: DUT_MotionStage;
	fbMotionStage: FB_MotionStage;
	nCounter: UINT;
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbMotionStage(stMotionStage:=M1);
nCounter := nCounter + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>